/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./public/**/*.{html,js}", "./public/*.html"],
  theme: {
    extend: {
      "colors": {
        "on-primary-fixed-variant": "#3f465c",
        "on-tertiary-container": "#008ebf",
        "surface-container-highest": "#e0e3e5",
        "primary-container": "#131b2e",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary": "#000000",
        "secondary-fixed-dim": "#ffb783",
        "on-tertiary-fixed-variant": "#004c69",
        "surface-variant": "#e0e3e5",
        "on-tertiary-fixed": "#001e2c",
        "on-surface": "#191c1e",
        "surface-bright": "#f7f9fb",
        "tertiary-fixed": "#c4e7ff",
        "primary-fixed": "#dae2fd",
        "tertiary-container": "#001e2c",
        "on-surface-variant": "#45464d",
        "surface": "#f7f9fb",
        "secondary": "#944a00",
        "background": "#f7f9fb",
        "on-secondary-container": "#693300",
        "surface-container": "#eceef0",
        "surface-tint": "#565e74",
        "on-background": "#191c1e",
        "on-secondary-fixed": "#301400",
        "inverse-surface": "#2d3133",
        "inverse-primary": "#bec6e0",
        "on-primary-fixed": "#131b2e",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "outline": "#76777d",
        "surface-dim": "#d8dadc",
        "surface-container-high": "#e6e8ea",
        "secondary-fixed": "#ffdcc5",
        "on-secondary-fixed-variant": "#713700",
        "surface-container-low": "#f2f4f6",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-container": "#7c839b",
        "error-container": "#ffdad6",
        "secondary-container": "#fd933d",
        "primary": "#000000",
        "inverse-on-surface": "#eff1f3",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#7bd0ff",
        "outline-variant": "#c6c6cd"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "fontFamily": {
        "body-md": ["Lexend"],
        "label-bold": ["Lexend"],
        "display-stat": ["Lexend"],
        "body-lg": ["Lexend"],
        "stat-label": ["Lexend"],
        "headline-md": ["Lexend"],
        "headline-lg": ["Lexend"]
      },
      "fontSize": {
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-bold": ["14px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "display-stat": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "stat-label": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
